spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
  jwt:
    secret: ${JWT_SECRET}

external:
  keys:
    durunubi: ${DURUNUBI_API_KEY}
    kakao:
      rest-key: ${KAKAO_REST_KEY}
    gpt: ${GPT_API_KEY}

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}