spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            scope : account_email, profile_nickname, profile_image
            authorization-grant-type: authorization_code
            redirect-uri: https://odorok.duckdns.org/api/auth/oauth2/kakao
            client-name: kakao
            client-authentication-method: client_secret_post
            password-secret: ${KAKAO_PASSWORD_SECRET}

  jwt:
    secret: ${JWT_SECRET}

external:
  keys:
    durunubi: ${DURUNUBI_API_KEY}
    kakao:
      rest-key: ${KAKAO_REST_KEY}
    gpt: ${GPT_API_KEY}

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}